### ISSUE TITLE
paridisp

### ISSUE THREAD

**Issue by FabioZTessitore** [MarcoDaniello/HelloWorld#4]
controlla l'elif

**Comment by MarcoDaniello** [comment]
adesso controllo

**Comment by MarcoDaniello** [comment]
prof ho messo else al posto di elif. 
è l'unica cosa che posso modificare

**Comment by FabioZTessitore** [comment]
va bene mettere else, perché se un numero non è pari c'è solo l'alternativa dispari. Però non si usa così

**Comment by MarcoDaniello** [comment]
va bene.
